/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: enums.proto */

#ifndef PROTOBUF_C_enums_2eproto__INCLUDED
#define PROTOBUF_C_enums_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _UnitType {
  UNIT_TYPE__CHARACTER = 0,
  UNIT_TYPE__CREATURE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(UNIT_TYPE)
} UnitType;
typedef enum _CharacterClass {
  CHARACTER_CLASS__WARRIOR = 0,
  CHARACTER_CLASS__MAGE = 1,
  CHARACTER_CLASS__PRIEST = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CHARACTER_CLASS)
} CharacterClass;
typedef enum _CreatureCategory {
  CREATURE_CATEGORY__NORMAL = 0,
  CREATURE_CATEGORY__ELITE = 1,
  CREATURE_CATEGORY__BOSS = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CREATURE_CATEGORY)
} CreatureCategory;
typedef enum _CreatureState {
  CREATURE_STATE__WANDERING = 0,
  CREATURE_STATE__COMBAT = 1,
  CREATURE_STATE__DEAD = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CREATURE_STATE)
} CreatureState;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    unit_type__descriptor;
extern const ProtobufCEnumDescriptor    character_class__descriptor;
extern const ProtobufCEnumDescriptor    creature_category__descriptor;
extern const ProtobufCEnumDescriptor    creature_state__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_enums_2eproto__INCLUDED */
