/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   welcome_message__init
                     (WelcomeMessage         *message)
{
  static const WelcomeMessage init_value = WELCOME_MESSAGE__INIT;
  *message = init_value;
}
size_t welcome_message__get_packed_size
                     (const WelcomeMessage *message)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t welcome_message__pack
                     (const WelcomeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t welcome_message__pack_to_buffer
                     (const WelcomeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WelcomeMessage *
       welcome_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WelcomeMessage *)
     protobuf_c_message_unpack (&welcome_message__descriptor,
                                allocator, len, data);
}
void   welcome_message__free_unpacked
                     (WelcomeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &welcome_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   world_state_message__init
                     (WorldStateMessage         *message)
{
  static const WorldStateMessage init_value = WORLD_STATE_MESSAGE__INIT;
  *message = init_value;
}
size_t world_state_message__get_packed_size
                     (const WorldStateMessage *message)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t world_state_message__pack
                     (const WorldStateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t world_state_message__pack_to_buffer
                     (const WorldStateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WorldStateMessage *
       world_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WorldStateMessage *)
     protobuf_c_message_unpack (&world_state_message__descriptor,
                                allocator, len, data);
}
void   world_state_message__free_unpacked
                     (WorldStateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &world_state_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events_message__init
                     (EventsMessage         *message)
{
  static const EventsMessage init_value = EVENTS_MESSAGE__INIT;
  *message = init_value;
}
size_t events_message__get_packed_size
                     (const EventsMessage *message)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events_message__pack
                     (const EventsMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events_message__pack_to_buffer
                     (const EventsMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EventsMessage *
       events_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EventsMessage *)
     protobuf_c_message_unpack (&events_message__descriptor,
                                allocator, len, data);
}
void   events_message__free_unpacked
                     (EventsMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &events_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   refuse_login_message__init
                     (RefuseLoginMessage         *message)
{
  static const RefuseLoginMessage init_value = REFUSE_LOGIN_MESSAGE__INIT;
  *message = init_value;
}
size_t refuse_login_message__get_packed_size
                     (const RefuseLoginMessage *message)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t refuse_login_message__pack
                     (const RefuseLoginMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t refuse_login_message__pack_to_buffer
                     (const RefuseLoginMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RefuseLoginMessage *
       refuse_login_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RefuseLoginMessage *)
     protobuf_c_message_unpack (&refuse_login_message__descriptor,
                                allocator, len, data);
}
void   refuse_login_message__free_unpacked
                     (RefuseLoginMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   character_message__init
                     (CharacterMessage         *message)
{
  static const CharacterMessage init_value = CHARACTER_MESSAGE__INIT;
  *message = init_value;
}
size_t character_message__get_packed_size
                     (const CharacterMessage *message)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t character_message__pack
                     (const CharacterMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t character_message__pack_to_buffer
                     (const CharacterMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CharacterMessage *
       character_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CharacterMessage *)
     protobuf_c_message_unpack (&character_message__descriptor,
                                allocator, len, data);
}
void   character_message__free_unpacked
                     (CharacterMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &character_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   creature_message__init
                     (CreatureMessage         *message)
{
  static const CreatureMessage init_value = CREATURE_MESSAGE__INIT;
  *message = init_value;
}
size_t creature_message__get_packed_size
                     (const CreatureMessage *message)
{
  assert(message->base.descriptor == &creature_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t creature_message__pack
                     (const CreatureMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &creature_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t creature_message__pack_to_buffer
                     (const CreatureMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &creature_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreatureMessage *
       creature_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreatureMessage *)
     protobuf_c_message_unpack (&creature_message__descriptor,
                                allocator, len, data);
}
void   creature_message__free_unpacked
                     (CreatureMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &creature_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   move_message__init
                     (MoveMessage         *message)
{
  static const MoveMessage init_value = MOVE_MESSAGE__INIT;
  *message = init_value;
}
size_t move_message__get_packed_size
                     (const MoveMessage *message)
{
  assert(message->base.descriptor == &move_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t move_message__pack
                     (const MoveMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &move_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t move_message__pack_to_buffer
                     (const MoveMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &move_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MoveMessage *
       move_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MoveMessage *)
     protobuf_c_message_unpack (&move_message__descriptor,
                                allocator, len, data);
}
void   move_message__free_unpacked
                     (MoveMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &move_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   logout_message__init
                     (LogoutMessage         *message)
{
  static const LogoutMessage init_value = LOGOUT_MESSAGE__INIT;
  *message = init_value;
}
size_t logout_message__get_packed_size
                     (const LogoutMessage *message)
{
  assert(message->base.descriptor == &logout_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t logout_message__pack
                     (const LogoutMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &logout_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t logout_message__pack_to_buffer
                     (const LogoutMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &logout_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LogoutMessage *
       logout_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LogoutMessage *)
     protobuf_c_message_unpack (&logout_message__descriptor,
                                allocator, len, data);
}
void   logout_message__free_unpacked
                     (LogoutMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &logout_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   skill_message__init
                     (SkillMessage         *message)
{
  static const SkillMessage init_value = SKILL_MESSAGE__INIT;
  *message = init_value;
}
size_t skill_message__get_packed_size
                     (const SkillMessage *message)
{
  assert(message->base.descriptor == &skill_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skill_message__pack
                     (const SkillMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skill_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skill_message__pack_to_buffer
                     (const SkillMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skill_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SkillMessage *
       skill_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SkillMessage *)
     protobuf_c_message_unpack (&skill_message__descriptor,
                                allocator, len, data);
}
void   skill_message__free_unpacked
                     (SkillMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skill_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   creature_state_change_message__init
                     (CreatureStateChangeMessage         *message)
{
  static const CreatureStateChangeMessage init_value = CREATURE_STATE_CHANGE_MESSAGE__INIT;
  *message = init_value;
}
size_t creature_state_change_message__get_packed_size
                     (const CreatureStateChangeMessage *message)
{
  assert(message->base.descriptor == &creature_state_change_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t creature_state_change_message__pack
                     (const CreatureStateChangeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &creature_state_change_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t creature_state_change_message__pack_to_buffer
                     (const CreatureStateChangeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &creature_state_change_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CreatureStateChangeMessage *
       creature_state_change_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CreatureStateChangeMessage *)
     protobuf_c_message_unpack (&creature_state_change_message__descriptor,
                                allocator, len, data);
}
void   creature_state_change_message__free_unpacked
                     (CreatureStateChangeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &creature_state_change_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reset_key_message__init
                     (ResetKeyMessage         *message)
{
  static const ResetKeyMessage init_value = RESET_KEY_MESSAGE__INIT;
  *message = init_value;
}
size_t reset_key_message__get_packed_size
                     (const ResetKeyMessage *message)
{
  assert(message->base.descriptor == &reset_key_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reset_key_message__pack
                     (const ResetKeyMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reset_key_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reset_key_message__pack_to_buffer
                     (const ResetKeyMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reset_key_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ResetKeyMessage *
       reset_key_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ResetKeyMessage *)
     protobuf_c_message_unpack (&reset_key_message__descriptor,
                                allocator, len, data);
}
void   reset_key_message__free_unpacked
                     (ResetKeyMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reset_key_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue response__type__enum_values_by_number[5] =
{
  { "WELCOME_MESSAGE", "RESPONSE__TYPE__WELCOME_MESSAGE", 0 },
  { "REFUSE_LOGIN", "RESPONSE__TYPE__REFUSE_LOGIN", 1 },
  { "WORLD_STATE", "RESPONSE__TYPE__WORLD_STATE", 2 },
  { "EVENTS", "RESPONSE__TYPE__EVENTS", 4 },
  { "RESET_KEY", "RESPONSE__TYPE__RESET_KEY", 5 },
};
static const ProtobufCIntRange response__type__value_ranges[] = {
{0, 0},{4, 3},{0, 5}
};
static const ProtobufCEnumValueIndex response__type__enum_values_by_name[5] =
{
  { "EVENTS", 3 },
  { "REFUSE_LOGIN", 1 },
  { "RESET_KEY", 4 },
  { "WELCOME_MESSAGE", 0 },
  { "WORLD_STATE", 2 },
};
const ProtobufCEnumDescriptor response__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.Type",
  "Type",
  "Response__Type",
  "",
  5,
  response__type__enum_values_by_number,
  5,
  response__type__enum_values_by_name,
  2,
  response__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &response__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "welcomeMsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, welcomemsg),
    &welcome_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refuseLogin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, refuselogin),
    &refuse_login_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "worldState",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, worldstate),
    &world_state_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, events),
    &events_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "resetKey",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, resetkey),
    &reset_key_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  4,   /* field[4] = events */
  2,   /* field[2] = refuseLogin */
  5,   /* field[5] = resetKey */
  0,   /* field[0] = type */
  1,   /* field[1] = welcomeMsg */
  3,   /* field[3] = worldState */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  6,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor welcome_message__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned welcome_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
};
static const ProtobufCIntRange welcome_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor welcome_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WelcomeMessage",
  "WelcomeMessage",
  "WelcomeMessage",
  "",
  sizeof(WelcomeMessage),
  2,
  welcome_message__field_descriptors,
  welcome_message__field_indices_by_name,
  1,  welcome_message__number_ranges,
  (ProtobufCMessageInit) welcome_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor world_state_message__field_descriptors[2] =
{
  {
    "charters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldStateMessage, n_charters),
    offsetof(WorldStateMessage, charters),
    &character_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "creatures",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldStateMessage, n_creatures),
    offsetof(WorldStateMessage, creatures),
    &creature_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned world_state_message__field_indices_by_name[] = {
  0,   /* field[0] = charters */
  1,   /* field[1] = creatures */
};
static const ProtobufCIntRange world_state_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor world_state_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WorldStateMessage",
  "WorldStateMessage",
  "WorldStateMessage",
  "",
  sizeof(WorldStateMessage),
  2,
  world_state_message__field_descriptors,
  world_state_message__field_indices_by_name,
  1,  world_state_message__number_ranges,
  (ProtobufCMessageInit) world_state_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events_message__field_descriptors[6] =
{
  {
    "moves",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_moves),
    offsetof(EventsMessage, moves),
    &move_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aimoves",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_aimoves),
    offsetof(EventsMessage, aimoves),
    &move_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newcomers",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_newcomers),
    offsetof(EventsMessage, newcomers),
    &character_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "logouts",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_logouts),
    offsetof(EventsMessage, logouts),
    &logout_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skills",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_skills),
    offsetof(EventsMessage, skills),
    &skill_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cschanges",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_cschanges),
    offsetof(EventsMessage, cschanges),
    &creature_state_change_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events_message__field_indices_by_name[] = {
  1,   /* field[1] = aimoves */
  5,   /* field[5] = cschanges */
  3,   /* field[3] = logouts */
  0,   /* field[0] = moves */
  2,   /* field[2] = newcomers */
  4,   /* field[4] = skills */
};
static const ProtobufCIntRange events_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor events_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EventsMessage",
  "EventsMessage",
  "EventsMessage",
  "",
  sizeof(EventsMessage),
  6,
  events_message__field_descriptors,
  events_message__field_indices_by_name,
  1,  events_message__number_ranges,
  (ProtobufCMessageInit) events_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue refuse_login_message__refuse_type__enum_values_by_number[3] =
{
  { "NICKNAME_TAKEN", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__NICKNAME_TAKEN", 1 },
  { "WRONG_CLASS", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__WRONG_CLASS", 2 },
  { "UNKNOWN", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__UNKNOWN", 3 },
};
static const ProtobufCIntRange refuse_login_message__refuse_type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex refuse_login_message__refuse_type__enum_values_by_name[3] =
{
  { "NICKNAME_TAKEN", 0 },
  { "UNKNOWN", 2 },
  { "WRONG_CLASS", 1 },
};
const ProtobufCEnumDescriptor refuse_login_message__refuse_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage.RefuseType",
  "RefuseType",
  "RefuseLoginMessage__RefuseType",
  "",
  3,
  refuse_login_message__refuse_type__enum_values_by_number,
  3,
  refuse_login_message__refuse_type__enum_values_by_name,
  1,
  refuse_login_message__refuse_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor refuse_login_message__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RefuseLoginMessage, type),
    &refuse_login_message__refuse_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned refuse_login_message__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange refuse_login_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor refuse_login_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "",
  sizeof(RefuseLoginMessage),
  1,
  refuse_login_message__field_descriptors,
  refuse_login_message__field_indices_by_name,
  1,  refuse_login_message__number_ranges,
  (ProtobufCMessageInit) refuse_login_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor character_message__field_descriptors[12] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, class_),
    &character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, exp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ad",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, ad),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_hp",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, max_hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_mp",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, max_mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned character_message__field_indices_by_name[] = {
  9,   /* field[9] = ad */
  2,   /* field[2] = class */
  4,   /* field[4] = exp */
  7,   /* field[7] = hp */
  0,   /* field[0] = id */
  3,   /* field[3] = level */
  10,   /* field[10] = max_hp */
  11,   /* field[11] = max_mp */
  8,   /* field[8] = mp */
  1,   /* field[1] = nickname */
  6,   /* field[6] = pos_x */
  5,   /* field[5] = pos_y */
};
static const ProtobufCIntRange character_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor character_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CharacterMessage",
  "CharacterMessage",
  "CharacterMessage",
  "",
  sizeof(CharacterMessage),
  12,
  character_message__field_descriptors,
  character_message__field_indices_by_name,
  1,  character_message__number_ranges,
  (ProtobufCMessageInit) character_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor creature_message__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "category",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, category),
    &creature_category__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_hp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, max_hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, exp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreatureMessage, state),
    &creature_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned creature_message__field_indices_by_name[] = {
  1,   /* field[1] = category */
  7,   /* field[7] = exp */
  5,   /* field[5] = hp */
  0,   /* field[0] = id */
  2,   /* field[2] = level */
  6,   /* field[6] = max_hp */
  4,   /* field[4] = pos_x */
  3,   /* field[3] = pos_y */
  8,   /* field[8] = state */
};
static const ProtobufCIntRange creature_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor creature_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreatureMessage",
  "CreatureMessage",
  "CreatureMessage",
  "",
  sizeof(CreatureMessage),
  9,
  creature_message__field_descriptors,
  creature_message__field_indices_by_name,
  1,  creature_message__number_ranges,
  (ProtobufCMessageInit) creature_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor move_message__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned move_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = pos_x */
  1,   /* field[1] = pos_y */
};
static const ProtobufCIntRange move_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor move_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MoveMessage",
  "MoveMessage",
  "MoveMessage",
  "",
  sizeof(MoveMessage),
  3,
  move_message__field_descriptors,
  move_message__field_indices_by_name,
  1,  move_message__number_ranges,
  (ProtobufCMessageInit) move_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor logout_message__field_descriptors[1] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LogoutMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned logout_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
};
static const ProtobufCIntRange logout_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor logout_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LogoutMessage",
  "LogoutMessage",
  "LogoutMessage",
  "",
  sizeof(LogoutMessage),
  1,
  logout_message__field_descriptors,
  logout_message__field_indices_by_name,
  1,  logout_message__number_ranges,
  (ProtobufCMessageInit) logout_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor skill_message__field_descriptors[7] =
{
  {
    "source_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, source_type),
    &unit_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, source_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, target_type),
    &unit_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, target_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skill",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, skill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_mp",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, source_mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_hp",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillMessage, target_hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skill_message__field_indices_by_name[] = {
  4,   /* field[4] = skill */
  1,   /* field[1] = source_id */
  5,   /* field[5] = source_mp */
  0,   /* field[0] = source_type */
  6,   /* field[6] = target_hp */
  3,   /* field[3] = target_id */
  2,   /* field[2] = target_type */
};
static const ProtobufCIntRange skill_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor skill_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SkillMessage",
  "SkillMessage",
  "SkillMessage",
  "",
  sizeof(SkillMessage),
  7,
  skill_message__field_descriptors,
  skill_message__field_indices_by_name,
  1,  skill_message__number_ranges,
  (ProtobufCMessageInit) skill_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor creature_state_change_message__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CreatureStateChangeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "state",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CreatureStateChangeMessage, state),
    &creature_state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned creature_state_change_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = state */
};
static const ProtobufCIntRange creature_state_change_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor creature_state_change_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CreatureStateChangeMessage",
  "CreatureStateChangeMessage",
  "CreatureStateChangeMessage",
  "",
  sizeof(CreatureStateChangeMessage),
  2,
  creature_state_change_message__field_descriptors,
  creature_state_change_message__field_indices_by_name,
  1,  creature_state_change_message__number_ranges,
  (ProtobufCMessageInit) creature_state_change_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reset_key_message__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ResetKeyMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reset_key_message__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange reset_key_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor reset_key_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ResetKeyMessage",
  "ResetKeyMessage",
  "ResetKeyMessage",
  "",
  sizeof(ResetKeyMessage),
  1,
  reset_key_message__field_descriptors,
  reset_key_message__field_indices_by_name,
  1,  reset_key_message__number_ranges,
  (ProtobufCMessageInit) reset_key_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
