/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   welcome_message__init
                     (WelcomeMessage         *message)
{
  static const WelcomeMessage init_value = WELCOME_MESSAGE__INIT;
  *message = init_value;
}
size_t welcome_message__get_packed_size
                     (const WelcomeMessage *message)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t welcome_message__pack
                     (const WelcomeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t welcome_message__pack_to_buffer
                     (const WelcomeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WelcomeMessage *
       welcome_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WelcomeMessage *)
     protobuf_c_message_unpack (&welcome_message__descriptor,
                                allocator, len, data);
}
void   welcome_message__free_unpacked
                     (WelcomeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &welcome_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor welcome_message__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned welcome_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
};
static const ProtobufCIntRange welcome_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor welcome_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WelcomeMessage",
  "WelcomeMessage",
  "WelcomeMessage",
  "",
  sizeof(WelcomeMessage),
  2,
  welcome_message__field_descriptors,
  welcome_message__field_indices_by_name,
  1,  welcome_message__number_ranges,
  (ProtobufCMessageInit) welcome_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response__request_type__enum_values_by_number[2] =
{
  { "WELCOME_MESSAGE", "RESPONSE__REQUEST_TYPE__WELCOME_MESSAGE", 0 },
  { "LOGIN_FAIL", "RESPONSE__REQUEST_TYPE__LOGIN_FAIL", 1 },
};
static const ProtobufCIntRange response__request_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex response__request_type__enum_values_by_name[2] =
{
  { "LOGIN_FAIL", 1 },
  { "WELCOME_MESSAGE", 0 },
};
const ProtobufCEnumDescriptor response__request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.RequestType",
  "RequestType",
  "Response__RequestType",
  "",
  2,
  response__request_type__enum_values_by_number,
  2,
  response__request_type__enum_values_by_name,
  1,
  response__request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &response__request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "welcomeMsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, welcomemsg),
    &welcome_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = welcomeMsg */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
