/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: enums.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "enums.pb-c.h"
static const ProtobufCEnumValue character_class__enum_values_by_number[3] =
{
  { "WARRIOR", "CHARACTER_CLASS__WARRIOR", 0 },
  { "MAGE", "CHARACTER_CLASS__MAGE", 1 },
  { "PRIEST", "CHARACTER_CLASS__PRIEST", 2 },
};
static const ProtobufCIntRange character_class__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex character_class__enum_values_by_name[3] =
{
  { "MAGE", 1 },
  { "PRIEST", 2 },
  { "WARRIOR", 0 },
};
const ProtobufCEnumDescriptor character_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CharacterClass",
  "CharacterClass",
  "CharacterClass",
  "",
  3,
  character_class__enum_values_by_number,
  3,
  character_class__enum_values_by_name,
  1,
  character_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue creature_category__enum_values_by_number[3] =
{
  { "NORMAL", "CREATURE_CATEGORY__NORMAL", 0 },
  { "ELITE", "CREATURE_CATEGORY__ELITE", 1 },
  { "BOSS", "CREATURE_CATEGORY__BOSS", 2 },
};
static const ProtobufCIntRange creature_category__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex creature_category__enum_values_by_name[3] =
{
  { "BOSS", 2 },
  { "ELITE", 1 },
  { "NORMAL", 0 },
};
const ProtobufCEnumDescriptor creature_category__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreatureCategory",
  "CreatureCategory",
  "CreatureCategory",
  "",
  3,
  creature_category__enum_values_by_number,
  3,
  creature_category__enum_values_by_name,
  1,
  creature_category__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue creature_state__enum_values_by_number[3] =
{
  { "PEACE", "CREATURE_STATE__PEACE", 0 },
  { "COMBAT", "CREATURE_STATE__COMBAT", 1 },
  { "DEAD", "CREATURE_STATE__DEAD", 2 },
};
static const ProtobufCIntRange creature_state__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex creature_state__enum_values_by_name[3] =
{
  { "COMBAT", 1 },
  { "DEAD", 2 },
  { "PEACE", 0 },
};
const ProtobufCEnumDescriptor creature_state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CreatureState",
  "CreatureState",
  "CreatureState",
  "",
  3,
  creature_state__enum_values_by_number,
  3,
  creature_state__enum_values_by_name,
  1,
  creature_state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
