/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   login_request__init
                     (LoginRequest         *message)
{
  static const LoginRequest init_value = LOGIN_REQUEST__INIT;
  *message = init_value;
}
size_t login_request__get_packed_size
                     (const LoginRequest *message)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_request__pack
                     (const LoginRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_request__pack_to_buffer
                     (const LoginRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginRequest *
       login_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginRequest *)
     protobuf_c_message_unpack (&login_request__descriptor,
                                allocator, len, data);
}
void   login_request__free_unpacked
                     (LoginRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor login_request__field_descriptors[2] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, class_),
    &character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_request__field_indices_by_name[] = {
  1,   /* field[1] = class */
  0,   /* field[0] = nickname */
};
static const ProtobufCIntRange login_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginRequest",
  "LoginRequest",
  "LoginRequest",
  "",
  sizeof(LoginRequest),
  2,
  login_request__field_descriptors,
  login_request__field_indices_by_name,
  1,  login_request__number_ranges,
  (ProtobufCMessageInit) login_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, type),
    &request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, login),
    &login_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = key */
  2,   /* field[2] = login */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  3,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue request_type__enum_values_by_number[1] =
{
  { "LOGIN", "REQUEST_TYPE__LOGIN", 0 },
};
static const ProtobufCIntRange request_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex request_type__enum_values_by_name[1] =
{
  { "LOGIN", 0 },
};
const ProtobufCEnumDescriptor request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RequestType",
  "RequestType",
  "RequestType",
  "",
  1,
  request_type__enum_values_by_number,
  1,
  request_type__enum_values_by_name,
  1,
  request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue character_class__enum_values_by_number[3] =
{
  { "WARRIOR", "CHARACTER_CLASS__WARRIOR", 0 },
  { "MAGE", "CHARACTER_CLASS__MAGE", 1 },
  { "PRIEST", "CHARACTER_CLASS__PRIEST", 2 },
};
static const ProtobufCIntRange character_class__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex character_class__enum_values_by_name[3] =
{
  { "MAGE", 1 },
  { "PRIEST", 2 },
  { "WARRIOR", 0 },
};
const ProtobufCEnumDescriptor character_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CharacterClass",
  "CharacterClass",
  "CharacterClass",
  "",
  3,
  character_class__enum_values_by_number,
  3,
  character_class__enum_values_by_name,
  1,
  character_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
