/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "request.pb-c.h"
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_request__init
                     (LoginRequest         *message)
{
  static const LoginRequest init_value = LOGIN_REQUEST__INIT;
  *message = init_value;
}
size_t login_request__get_packed_size
                     (const LoginRequest *message)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_request__pack
                     (const LoginRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_request__pack_to_buffer
                     (const LoginRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginRequest *
       login_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginRequest *)
     protobuf_c_message_unpack (&login_request__descriptor,
                                allocator, len, data);
}
void   login_request__free_unpacked
                     (LoginRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &login_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   move_request__init
                     (MoveRequest         *message)
{
  static const MoveRequest init_value = MOVE_REQUEST__INIT;
  *message = init_value;
}
size_t move_request__get_packed_size
                     (const MoveRequest *message)
{
  assert(message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t move_request__pack
                     (const MoveRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t move_request__pack_to_buffer
                     (const MoveRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &move_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MoveRequest *
       move_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MoveRequest *)
     protobuf_c_message_unpack (&move_request__descriptor,
                                allocator, len, data);
}
void   move_request__free_unpacked
                     (MoveRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &move_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   skill_request__init
                     (SkillRequest         *message)
{
  static const SkillRequest init_value = SKILL_REQUEST__INIT;
  *message = init_value;
}
size_t skill_request__get_packed_size
                     (const SkillRequest *message)
{
  assert(message->base.descriptor == &skill_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t skill_request__pack
                     (const SkillRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &skill_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t skill_request__pack_to_buffer
                     (const SkillRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &skill_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SkillRequest *
       skill_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SkillRequest *)
     protobuf_c_message_unpack (&skill_request__descriptor,
                                allocator, len, data);
}
void   skill_request__free_unpacked
                     (SkillRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &skill_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue request__type__enum_values_by_number[4] =
{
  { "LOGIN", "REQUEST__TYPE__LOGIN", 0 },
  { "MOVE", "REQUEST__TYPE__MOVE", 1 },
  { "SKILL", "REQUEST__TYPE__SKILL", 2 },
  { "KEEP", "REQUEST__TYPE__KEEP", 4 },
};
static const ProtobufCIntRange request__type__value_ranges[] = {
{0, 0},{4, 3},{0, 4}
};
static const ProtobufCEnumValueIndex request__type__enum_values_by_name[4] =
{
  { "KEEP", 3 },
  { "LOGIN", 0 },
  { "MOVE", 1 },
  { "SKILL", 2 },
};
const ProtobufCEnumDescriptor request__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Request.Type",
  "Type",
  "Request__Type",
  "",
  4,
  request__type__enum_values_by_number,
  4,
  request__type__enum_values_by_name,
  2,
  request__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor request__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Request, type),
    &request__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Request, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "login",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, login),
    &login_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "move",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, move),
    &move_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "skill",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Request, skill),
    &skill_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  1,   /* field[1] = key */
  2,   /* field[2] = login */
  3,   /* field[3] = move */
  4,   /* field[4] = skill */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  5,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_request__field_descriptors[2] =
{
  {
    "nickname",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(LoginRequest, class_),
    &character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_request__field_indices_by_name[] = {
  1,   /* field[1] = class */
  0,   /* field[0] = nickname */
};
static const ProtobufCIntRange login_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginRequest",
  "LoginRequest",
  "LoginRequest",
  "",
  sizeof(LoginRequest),
  2,
  login_request__field_descriptors,
  login_request__field_indices_by_name,
  1,  login_request__number_ranges,
  (ProtobufCMessageInit) login_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor move_request__field_descriptors[2] =
{
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveRequest, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveRequest, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned move_request__field_indices_by_name[] = {
  0,   /* field[0] = pos_x */
  1,   /* field[1] = pos_y */
};
static const ProtobufCIntRange move_request__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor move_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MoveRequest",
  "MoveRequest",
  "MoveRequest",
  "",
  sizeof(MoveRequest),
  2,
  move_request__field_descriptors,
  move_request__field_indices_by_name,
  1,  move_request__number_ranges,
  (ProtobufCMessageInit) move_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor skill_request__field_descriptors[2] =
{
  {
    "skill",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillRequest, skill),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SkillRequest, target_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned skill_request__field_indices_by_name[] = {
  0,   /* field[0] = skill */
  1,   /* field[1] = target_id */
};
static const ProtobufCIntRange skill_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor skill_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SkillRequest",
  "SkillRequest",
  "SkillRequest",
  "",
  sizeof(SkillRequest),
  2,
  skill_request__field_descriptors,
  skill_request__field_indices_by_name,
  1,  skill_request__number_ranges,
  (ProtobufCMessageInit) skill_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
