/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   welcome_message__init
                     (WelcomeMessage         *message)
{
  static const WelcomeMessage init_value = WELCOME_MESSAGE__INIT;
  *message = init_value;
}
size_t welcome_message__get_packed_size
                     (const WelcomeMessage *message)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t welcome_message__pack
                     (const WelcomeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t welcome_message__pack_to_buffer
                     (const WelcomeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WelcomeMessage *
       welcome_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WelcomeMessage *)
     protobuf_c_message_unpack (&welcome_message__descriptor,
                                allocator, len, data);
}
void   welcome_message__free_unpacked
                     (WelcomeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &welcome_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   world_state_message__init
                     (WorldStateMessage         *message)
{
  static const WorldStateMessage init_value = WORLD_STATE_MESSAGE__INIT;
  *message = init_value;
}
size_t world_state_message__get_packed_size
                     (const WorldStateMessage *message)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t world_state_message__pack
                     (const WorldStateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t world_state_message__pack_to_buffer
                     (const WorldStateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WorldStateMessage *
       world_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WorldStateMessage *)
     protobuf_c_message_unpack (&world_state_message__descriptor,
                                allocator, len, data);
}
void   world_state_message__free_unpacked
                     (WorldStateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &world_state_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   events_message__init
                     (EventsMessage         *message)
{
  static const EventsMessage init_value = EVENTS_MESSAGE__INIT;
  *message = init_value;
}
size_t events_message__get_packed_size
                     (const EventsMessage *message)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t events_message__pack
                     (const EventsMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t events_message__pack_to_buffer
                     (const EventsMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &events_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
EventsMessage *
       events_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (EventsMessage *)
     protobuf_c_message_unpack (&events_message__descriptor,
                                allocator, len, data);
}
void   events_message__free_unpacked
                     (EventsMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &events_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   refuse_login_message__init
                     (RefuseLoginMessage         *message)
{
  static const RefuseLoginMessage init_value = REFUSE_LOGIN_MESSAGE__INIT;
  *message = init_value;
}
size_t refuse_login_message__get_packed_size
                     (const RefuseLoginMessage *message)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t refuse_login_message__pack
                     (const RefuseLoginMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t refuse_login_message__pack_to_buffer
                     (const RefuseLoginMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RefuseLoginMessage *
       refuse_login_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RefuseLoginMessage *)
     protobuf_c_message_unpack (&refuse_login_message__descriptor,
                                allocator, len, data);
}
void   refuse_login_message__free_unpacked
                     (RefuseLoginMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   character_message__init
                     (CharacterMessage         *message)
{
  static const CharacterMessage init_value = CHARACTER_MESSAGE__INIT;
  *message = init_value;
}
size_t character_message__get_packed_size
                     (const CharacterMessage *message)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t character_message__pack
                     (const CharacterMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t character_message__pack_to_buffer
                     (const CharacterMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &character_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CharacterMessage *
       character_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CharacterMessage *)
     protobuf_c_message_unpack (&character_message__descriptor,
                                allocator, len, data);
}
void   character_message__free_unpacked
                     (CharacterMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &character_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   move_event_message__init
                     (MoveEventMessage         *message)
{
  static const MoveEventMessage init_value = MOVE_EVENT_MESSAGE__INIT;
  *message = init_value;
}
size_t move_event_message__get_packed_size
                     (const MoveEventMessage *message)
{
  assert(message->base.descriptor == &move_event_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t move_event_message__pack
                     (const MoveEventMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &move_event_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t move_event_message__pack_to_buffer
                     (const MoveEventMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &move_event_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MoveEventMessage *
       move_event_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MoveEventMessage *)
     protobuf_c_message_unpack (&move_event_message__descriptor,
                                allocator, len, data);
}
void   move_event_message__free_unpacked
                     (MoveEventMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &move_event_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   newcomer_event_message__init
                     (NewcomerEventMessage         *message)
{
  static const NewcomerEventMessage init_value = NEWCOMER_EVENT_MESSAGE__INIT;
  *message = init_value;
}
size_t newcomer_event_message__get_packed_size
                     (const NewcomerEventMessage *message)
{
  assert(message->base.descriptor == &newcomer_event_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t newcomer_event_message__pack
                     (const NewcomerEventMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &newcomer_event_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t newcomer_event_message__pack_to_buffer
                     (const NewcomerEventMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &newcomer_event_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NewcomerEventMessage *
       newcomer_event_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NewcomerEventMessage *)
     protobuf_c_message_unpack (&newcomer_event_message__descriptor,
                                allocator, len, data);
}
void   newcomer_event_message__free_unpacked
                     (NewcomerEventMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &newcomer_event_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue response__request_type__enum_values_by_number[4] =
{
  { "WELCOME_MESSAGE", "RESPONSE__REQUEST_TYPE__WELCOME_MESSAGE", 0 },
  { "REFUSE_LOGIN", "RESPONSE__REQUEST_TYPE__REFUSE_LOGIN", 1 },
  { "WORLD_STATE", "RESPONSE__REQUEST_TYPE__WORLD_STATE", 2 },
  { "EVENTS", "RESPONSE__REQUEST_TYPE__EVENTS", 4 },
};
static const ProtobufCIntRange response__request_type__value_ranges[] = {
{0, 0},{4, 3},{0, 4}
};
static const ProtobufCEnumValueIndex response__request_type__enum_values_by_name[4] =
{
  { "EVENTS", 3 },
  { "REFUSE_LOGIN", 1 },
  { "WELCOME_MESSAGE", 0 },
  { "WORLD_STATE", 2 },
};
const ProtobufCEnumDescriptor response__request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.RequestType",
  "RequestType",
  "Response__RequestType",
  "",
  4,
  response__request_type__enum_values_by_number,
  4,
  response__request_type__enum_values_by_name,
  2,
  response__request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &response__request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "welcomeMsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, welcomemsg),
    &welcome_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "refuseLogin",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, refuselogin),
    &refuse_login_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "worldState",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, worldstate),
    &world_state_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "events",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, events),
    &events_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  4,   /* field[4] = events */
  2,   /* field[2] = refuseLogin */
  0,   /* field[0] = type */
  1,   /* field[1] = welcomeMsg */
  3,   /* field[3] = worldState */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  5,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor welcome_message__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned welcome_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
};
static const ProtobufCIntRange welcome_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor welcome_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WelcomeMessage",
  "WelcomeMessage",
  "WelcomeMessage",
  "",
  sizeof(WelcomeMessage),
  2,
  welcome_message__field_descriptors,
  welcome_message__field_indices_by_name,
  1,  welcome_message__number_ranges,
  (ProtobufCMessageInit) welcome_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor world_state_message__field_descriptors[1] =
{
  {
    "charters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldStateMessage, n_charters),
    offsetof(WorldStateMessage, charters),
    &character_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned world_state_message__field_indices_by_name[] = {
  0,   /* field[0] = charters */
};
static const ProtobufCIntRange world_state_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor world_state_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WorldStateMessage",
  "WorldStateMessage",
  "WorldStateMessage",
  "",
  sizeof(WorldStateMessage),
  1,
  world_state_message__field_descriptors,
  world_state_message__field_indices_by_name,
  1,  world_state_message__number_ranges,
  (ProtobufCMessageInit) world_state_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor events_message__field_descriptors[2] =
{
  {
    "moveEvents",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_moveevents),
    offsetof(EventsMessage, moveevents),
    &move_event_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "newcomerEvents",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(EventsMessage, n_newcomerevents),
    offsetof(EventsMessage, newcomerevents),
    &newcomer_event_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned events_message__field_indices_by_name[] = {
  0,   /* field[0] = moveEvents */
  1,   /* field[1] = newcomerEvents */
};
static const ProtobufCIntRange events_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor events_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "EventsMessage",
  "EventsMessage",
  "EventsMessage",
  "",
  sizeof(EventsMessage),
  2,
  events_message__field_descriptors,
  events_message__field_indices_by_name,
  1,  events_message__number_ranges,
  (ProtobufCMessageInit) events_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue refuse_login_message__refuse_type__enum_values_by_number[3] =
{
  { "NICKNAME_TAKEN", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__NICKNAME_TAKEN", 1 },
  { "WRONG_CLASS", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__WRONG_CLASS", 2 },
  { "UNKNOWN", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__UNKNOWN", 3 },
};
static const ProtobufCIntRange refuse_login_message__refuse_type__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex refuse_login_message__refuse_type__enum_values_by_name[3] =
{
  { "NICKNAME_TAKEN", 0 },
  { "UNKNOWN", 2 },
  { "WRONG_CLASS", 1 },
};
const ProtobufCEnumDescriptor refuse_login_message__refuse_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage.RefuseType",
  "RefuseType",
  "RefuseLoginMessage__RefuseType",
  "",
  3,
  refuse_login_message__refuse_type__enum_values_by_number,
  3,
  refuse_login_message__refuse_type__enum_values_by_name,
  1,
  refuse_login_message__refuse_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor refuse_login_message__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RefuseLoginMessage, type),
    &refuse_login_message__refuse_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned refuse_login_message__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange refuse_login_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor refuse_login_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "",
  sizeof(RefuseLoginMessage),
  1,
  refuse_login_message__field_descriptors,
  refuse_login_message__field_indices_by_name,
  1,  refuse_login_message__number_ranges,
  (ProtobufCMessageInit) refuse_login_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue character_message__character_class__enum_values_by_number[3] =
{
  { "WARRIOR", "CHARACTER_MESSAGE__CHARACTER_CLASS__WARRIOR", 0 },
  { "MAGE", "CHARACTER_MESSAGE__CHARACTER_CLASS__MAGE", 2 },
  { "PRIEST", "CHARACTER_MESSAGE__CHARACTER_CLASS__PRIEST", 3 },
};
static const ProtobufCIntRange character_message__character_class__value_ranges[] = {
{0, 0},{2, 1},{0, 3}
};
static const ProtobufCEnumValueIndex character_message__character_class__enum_values_by_name[3] =
{
  { "MAGE", 1 },
  { "PRIEST", 2 },
  { "WARRIOR", 0 },
};
const ProtobufCEnumDescriptor character_message__character_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CharacterMessage.CharacterClass",
  "CharacterClass",
  "CharacterMessage__CharacterClass",
  "",
  3,
  character_message__character_class__enum_values_by_number,
  3,
  character_message__character_class__enum_values_by_name,
  2,
  character_message__character_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor character_message__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, class_),
    &character_message__character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, exp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(CharacterMessage, mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned character_message__field_indices_by_name[] = {
  2,   /* field[2] = class */
  4,   /* field[4] = exp */
  7,   /* field[7] = hp */
  0,   /* field[0] = id */
  3,   /* field[3] = level */
  8,   /* field[8] = mp */
  1,   /* field[1] = nickname */
  6,   /* field[6] = pos_x */
  5,   /* field[5] = pos_y */
};
static const ProtobufCIntRange character_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor character_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CharacterMessage",
  "CharacterMessage",
  "CharacterMessage",
  "",
  sizeof(CharacterMessage),
  9,
  character_message__field_descriptors,
  character_message__field_indices_by_name,
  1,  character_message__number_ranges,
  (ProtobufCMessageInit) character_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor move_event_message__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveEventMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveEventMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(MoveEventMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned move_event_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = pos_x */
  1,   /* field[1] = pos_y */
};
static const ProtobufCIntRange move_event_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor move_event_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MoveEventMessage",
  "MoveEventMessage",
  "MoveEventMessage",
  "",
  sizeof(MoveEventMessage),
  3,
  move_event_message__field_descriptors,
  move_event_message__field_indices_by_name,
  1,  move_event_message__number_ranges,
  (ProtobufCMessageInit) move_event_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue newcomer_event_message__character_class__enum_values_by_number[3] =
{
  { "WARRIOR", "NEWCOMER_EVENT_MESSAGE__CHARACTER_CLASS__WARRIOR", 0 },
  { "MAGE", "NEWCOMER_EVENT_MESSAGE__CHARACTER_CLASS__MAGE", 2 },
  { "PRIEST", "NEWCOMER_EVENT_MESSAGE__CHARACTER_CLASS__PRIEST", 3 },
};
static const ProtobufCIntRange newcomer_event_message__character_class__value_ranges[] = {
{0, 0},{2, 1},{0, 3}
};
static const ProtobufCEnumValueIndex newcomer_event_message__character_class__enum_values_by_name[3] =
{
  { "MAGE", 1 },
  { "PRIEST", 2 },
  { "WARRIOR", 0 },
};
const ProtobufCEnumDescriptor newcomer_event_message__character_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NewcomerEventMessage.CharacterClass",
  "CharacterClass",
  "NewcomerEventMessage__CharacterClass",
  "",
  3,
  newcomer_event_message__character_class__enum_values_by_number,
  3,
  newcomer_event_message__character_class__enum_values_by_name,
  2,
  newcomer_event_message__character_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor newcomer_event_message__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, class_),
    &newcomer_event_message__character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, exp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NewcomerEventMessage, mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned newcomer_event_message__field_indices_by_name[] = {
  2,   /* field[2] = class */
  4,   /* field[4] = exp */
  7,   /* field[7] = hp */
  0,   /* field[0] = id */
  3,   /* field[3] = level */
  8,   /* field[8] = mp */
  1,   /* field[1] = nickname */
  6,   /* field[6] = pos_x */
  5,   /* field[5] = pos_y */
};
static const ProtobufCIntRange newcomer_event_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor newcomer_event_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NewcomerEventMessage",
  "NewcomerEventMessage",
  "NewcomerEventMessage",
  "",
  sizeof(NewcomerEventMessage),
  9,
  newcomer_event_message__field_descriptors,
  newcomer_event_message__field_indices_by_name,
  1,  newcomer_event_message__number_ranges,
  (ProtobufCMessageInit) newcomer_event_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
