/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: response.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "response.pb-c.h"
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   welcome_message__init
                     (WelcomeMessage         *message)
{
  static const WelcomeMessage init_value = WELCOME_MESSAGE__INIT;
  *message = init_value;
}
size_t welcome_message__get_packed_size
                     (const WelcomeMessage *message)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t welcome_message__pack
                     (const WelcomeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t welcome_message__pack_to_buffer
                     (const WelcomeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &welcome_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WelcomeMessage *
       welcome_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WelcomeMessage *)
     protobuf_c_message_unpack (&welcome_message__descriptor,
                                allocator, len, data);
}
void   welcome_message__free_unpacked
                     (WelcomeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &welcome_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   world_state_message__init
                     (WorldStateMessage         *message)
{
  static const WorldStateMessage init_value = WORLD_STATE_MESSAGE__INIT;
  *message = init_value;
}
size_t world_state_message__get_packed_size
                     (const WorldStateMessage *message)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t world_state_message__pack
                     (const WorldStateMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t world_state_message__pack_to_buffer
                     (const WorldStateMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &world_state_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
WorldStateMessage *
       world_state_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (WorldStateMessage *)
     protobuf_c_message_unpack (&world_state_message__descriptor,
                                allocator, len, data);
}
void   world_state_message__free_unpacked
                     (WorldStateMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &world_state_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   refuse_login_message__init
                     (RefuseLoginMessage         *message)
{
  static const RefuseLoginMessage init_value = REFUSE_LOGIN_MESSAGE__INIT;
  *message = init_value;
}
size_t refuse_login_message__get_packed_size
                     (const RefuseLoginMessage *message)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t refuse_login_message__pack
                     (const RefuseLoginMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t refuse_login_message__pack_to_buffer
                     (const RefuseLoginMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RefuseLoginMessage *
       refuse_login_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RefuseLoginMessage *)
     protobuf_c_message_unpack (&refuse_login_message__descriptor,
                                allocator, len, data);
}
void   refuse_login_message__free_unpacked
                     (RefuseLoginMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &refuse_login_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   character_status__init
                     (CharacterStatus         *message)
{
  static const CharacterStatus init_value = CHARACTER_STATUS__INIT;
  *message = init_value;
}
size_t character_status__get_packed_size
                     (const CharacterStatus *message)
{
  assert(message->base.descriptor == &character_status__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t character_status__pack
                     (const CharacterStatus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &character_status__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t character_status__pack_to_buffer
                     (const CharacterStatus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &character_status__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CharacterStatus *
       character_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CharacterStatus *)
     protobuf_c_message_unpack (&character_status__descriptor,
                                allocator, len, data);
}
void   character_status__free_unpacked
                     (CharacterStatus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &character_status__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue response__request_type__enum_values_by_number[3] =
{
  { "WELCOME_MESSAGE", "RESPONSE__REQUEST_TYPE__WELCOME_MESSAGE", 0 },
  { "LOGIN_FAIL", "RESPONSE__REQUEST_TYPE__LOGIN_FAIL", 1 },
  { "WORLD_STATE", "RESPONSE__REQUEST_TYPE__WORLD_STATE", 2 },
};
static const ProtobufCIntRange response__request_type__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex response__request_type__enum_values_by_name[3] =
{
  { "LOGIN_FAIL", 1 },
  { "WELCOME_MESSAGE", 0 },
  { "WORLD_STATE", 2 },
};
const ProtobufCEnumDescriptor response__request_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "Response.RequestType",
  "RequestType",
  "Response__RequestType",
  "",
  3,
  response__request_type__enum_values_by_number,
  3,
  response__request_type__enum_values_by_name,
  1,
  response__request_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, type),
    &response__request_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "welcomeMsg",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Response, welcomemsg),
    &welcome_message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = welcomeMsg */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor welcome_message__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(WelcomeMessage, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned welcome_message__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = key */
};
static const ProtobufCIntRange welcome_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor welcome_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WelcomeMessage",
  "WelcomeMessage",
  "WelcomeMessage",
  "",
  sizeof(WelcomeMessage),
  2,
  welcome_message__field_descriptors,
  welcome_message__field_indices_by_name,
  1,  welcome_message__number_ranges,
  (ProtobufCMessageInit) welcome_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor world_state_message__field_descriptors[1] =
{
  {
    "charters",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(WorldStateMessage, n_charters),
    offsetof(WorldStateMessage, charters),
    &character_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned world_state_message__field_indices_by_name[] = {
  0,   /* field[0] = charters */
};
static const ProtobufCIntRange world_state_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor world_state_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "WorldStateMessage",
  "WorldStateMessage",
  "WorldStateMessage",
  "",
  sizeof(WorldStateMessage),
  1,
  world_state_message__field_descriptors,
  world_state_message__field_indices_by_name,
  1,  world_state_message__number_ranges,
  (ProtobufCMessageInit) world_state_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue refuse_login_message__refuse_type__enum_values_by_number[1] =
{
  { "NICKNAME_TAKEN", "REFUSE_LOGIN_MESSAGE__REFUSE_TYPE__NICKNAME_TAKEN", 1 },
};
static const ProtobufCIntRange refuse_login_message__refuse_type__value_ranges[] = {
{1, 0},{0, 1}
};
static const ProtobufCEnumValueIndex refuse_login_message__refuse_type__enum_values_by_name[1] =
{
  { "NICKNAME_TAKEN", 0 },
};
const ProtobufCEnumDescriptor refuse_login_message__refuse_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage.RefuseType",
  "RefuseType",
  "RefuseLoginMessage__RefuseType",
  "",
  1,
  refuse_login_message__refuse_type__enum_values_by_number,
  1,
  refuse_login_message__refuse_type__enum_values_by_name,
  1,
  refuse_login_message__refuse_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor refuse_login_message__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(RefuseLoginMessage, type),
    &refuse_login_message__refuse_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned refuse_login_message__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange refuse_login_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor refuse_login_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "RefuseLoginMessage",
  "",
  sizeof(RefuseLoginMessage),
  1,
  refuse_login_message__field_descriptors,
  refuse_login_message__field_indices_by_name,
  1,  refuse_login_message__number_ranges,
  (ProtobufCMessageInit) refuse_login_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue character_status__character_class__enum_values_by_number[3] =
{
  { "WARRIOR", "CHARACTER_STATUS__CHARACTER_CLASS__WARRIOR", 0 },
  { "MAGE", "CHARACTER_STATUS__CHARACTER_CLASS__MAGE", 2 },
  { "PRIEST", "CHARACTER_STATUS__CHARACTER_CLASS__PRIEST", 3 },
};
static const ProtobufCIntRange character_status__character_class__value_ranges[] = {
{0, 0},{2, 1},{0, 3}
};
static const ProtobufCEnumValueIndex character_status__character_class__enum_values_by_name[3] =
{
  { "MAGE", 1 },
  { "PRIEST", 2 },
  { "WARRIOR", 0 },
};
const ProtobufCEnumDescriptor character_status__character_class__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "CharacterStatus.CharacterClass",
  "CharacterClass",
  "CharacterStatus__CharacterClass",
  "",
  3,
  character_status__character_class__enum_values_by_number,
  3,
  character_status__character_class__enum_values_by_name,
  2,
  character_status__character_class__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor character_status__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickname",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, nickname),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "class",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, class_),
    &character_status__character_class__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "level",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exp",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, exp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_y",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, pos_y),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pos_x",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, pos_x),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hp",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, hp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mp",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(CharacterStatus, mp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned character_status__field_indices_by_name[] = {
  2,   /* field[2] = class */
  4,   /* field[4] = exp */
  7,   /* field[7] = hp */
  0,   /* field[0] = id */
  3,   /* field[3] = level */
  8,   /* field[8] = mp */
  1,   /* field[1] = nickname */
  6,   /* field[6] = pos_x */
  5,   /* field[5] = pos_y */
};
static const ProtobufCIntRange character_status__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor character_status__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "CharacterStatus",
  "CharacterStatus",
  "CharacterStatus",
  "",
  sizeof(CharacterStatus),
  9,
  character_status__field_descriptors,
  character_status__field_indices_by_name,
  1,  character_status__number_ranges,
  (ProtobufCMessageInit) character_status__init,
  NULL,NULL,NULL    /* reserved[123] */
};
